import = ["~/.config/alacritty/local.toml"]

[cursor]
blink_interval = 600

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[scrolling]
history = 10000

[window]
decorations = "buttonless"
opacity = 0.95

[window.dimensions]
columns = 200
lines = 70

[window.padding]
x = 12
y = 10

[window.position]
x = 800
y = 100
