# config.yml
# This is the default configuration file for the e1s application.

# Debug mode: Set to true to enable debug mode, false to disable it.
debug: true

# JSON logging: Set to true to enable logging in JSON format, false for plain text.
#json: false

# Log file path: Specify the path to the log file.
# The default path is the system's temporary directory.
log-file: "/tmp/e1s.log"
# read-only mode: Set to true to enable read-only mode, false to allow changes.
#read-only: false

# Refresh rate: Specify the default refresh rate in seconds.
# Set to -1 to disable auto-refresh.
#refresh: 30

# Shell: Specify the interactive shell to use with ecs exec.
#shell: "/bin/sh"

# AWS profile: Specify the AWS profile to use for credentials.
#profile: ""

# AWS region: Specify the AWS region for the resources.
#region: ""

# theme
# https://github.com/keidarcy/alacritty-theme/blob/master/images/rose-pine.png
# theme: rose-pine

# Customize color theme
# hex colors example monokai from https://github.com/alacritty/alacritty-theme/blob/master/themes/monokai.toml
# colors:
#   BgColor: "#272822"
#   FgColor: "#f8f8f2"
#   BorderColor: "#a1efe4"
#   Black: "#272822"
#   Red: "#f92672"
#   Green: "#a6e22e"
#   Yellow: "#f4bf75"
#   Blue: "#66d9ef"
#   Magenta: "#ae81ff"
#   Cyan: "#a1efe4"
#   Gray: "#808080"
# W3C colors example
# colors:
#   BgColor: black
#   FgColor: cadeblue
#   BorderColor: dodgerblue
#   Black: black
#   Red: orangered
#   Green: palegreen
#   Yellow: greenyellow
#   Blue: darkslateblue
#   Magenta: mediumpurple
#   Cyan: lightskyblue
#   Gray: lightslategray
