[tools]
argocd = "latest"
bat = "latest"
bun = "1.2.11"
delta = "latest"
dust = "latest"
eksctl = "latest"
eza = "latest"
fd = "latest"
gh = "latest"
go = "latest"
hcl2json = "latest"
helm = "latest"
hugo = "latest"
k9s = "latest"
kind = "latest"
kubecolor = "latest"
kubectl = "latest"
mysql = "latest"
node = "latest"
pipx = "latest"
pnpm = "latest"
popeye = "latest"
rg = "latest"
ruby = "3.4.3"
rust = "latest"
sops = "latest"
terraform = "1.12.0"
tokei = "latest"
uv = "latest"
viddy = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

