[tools]
argocd = "latest"
bat = "latest"
bun = "1.2.11"
delta = "latest"
dust = "latest"
eksctl = "latest"
eza = "latest"
fd = "latest"
gh = "latest"
go = "latest"
helm = "latest"
hugo = "latest"
k9s = "latest"
kind = "latest"
kubecolor = "latest"
kubectl = "latest"
node = "latest"
pnpm = "latest"
popeye = "latest"
rg = "latest"
terraform = "1.11.0"
tokei = "latest"
uv = "latest"
viddy = "latest"
