[tools]
argocd = "latest"
dust = "latest"
eksctl = "latest"
helm = "latest"
hugo = "latest"
k9s = "latest"
kind = "latest"
kubecolor = "latest"
pnpm = "latest"
popeye = "latest"
terraform = "1.11.0"
viddy = "latest"
