#!/usr/bin/env zsh

emojis=$(curl -sSL 'https://git.io/JXXO7')

selected_emoji=$(echo $emojis | fzf)

echo $selected_emoji

if [[ "$(uname)" == "Darwin" ]]; then
    echo -n $selected_emoji | pbcopy
elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then
    echo -n $selected_emoji | xclip -selection c
fi
