#!/usr/bin/env bash

languages=$(echo "javascript bash typescript python php golang rust mongo" | tr " " "\n")
core_utils=$(echo "find xargs sed awk" | tr " " "\n")
selected=$(echo "$languages\n$core_utils" | fzf)

if [[ -z $selected ]]; then
    exit 0
fi

read -p "Enter Query: " query

if echo "$languages" | grep -qs $selected; then
    query=`echo $query | tr ' ' '+'`
    tmux neww bash -c "echo \"curl cht.sh/$selected/$query/\" & curl cht.sh/$selected/$query & while [ : ]; do sleep 1; done"
else
    tmux neww bash -c "echo \"curl -s cht.sh/$selected~$query/\" & curl -s cht.sh/$selected~$query | less"
fi
